import type { Metadata } from "next";
import s from "./page.module.scss";
import "./globals.scss";
import { NavBar } from "./components/nav-bar/Nav";
import { SessionProviderWrapper } from "./components/session-provider-wrapper/session-provider-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <NavBar />
        <SessionProviderWrapper>
          <div className={s.appContainer}>{children}</div>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
