import type { Metadata } from "next";
import s from "./page.module.scss";
import "./globals.scss";
import { NavBar } from "./components/nav-bar/Nav";
import { SessionProviderWrapper } from "./components/session-provider-wrapper/session-provider-wrapper";
import localFont from 'next/font/local';

const sora = localFont({
  src: '../styles/fonts/Sora-Regular.ttf',
  weight: '400', // Adjust based on your font's weight
  style: 'normal',
  variable: '--font-sora',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <NavBar customClassName={sora.className}/>
        <SessionProviderWrapper>
          <div className={`${s.appContainer} ${sora.className}`}>{children}</div>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
